language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t tchorzewski1991/react-docker-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true tchorzewski1991/react-docker-travis-aws npm run test